#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

echo "🚀 Starting Build Process..."

# 1. Build Frontend
if [ -f "package.json" ]; then
    echo "📦 Building Frontend..."
    npx mix --production
else
    echo "⚠️ package.json not found, skipping frontend build."
fi

# 2. Optimize Backend (Remove Dev Dependencies)
echo "🧹 Optimizing Composer for Production..."
# Using --no-dev to remove phpstan etc.
# Using --classmap-authoritative for maximum performance as discussed
composer install --no-dev --optimize-autoloader --classmap-authoritative

# 3. Create Zip
ZIP_NAME="fluent-smtp.zip"
echo "🤐 Creating $ZIP_NAME..."

# Remove previous build if exists
rm -f $ZIP_NAME

# Create the zip file excluding development files and folders
# We use -r for recursive, and -x to exclude patterns
#
# Dot-entries are excluded as a class rather than named one at a time. Listing
# them individually meant that every new tool dropping a dot-directory in here
# shipped to wordpress.org until somebody noticed - .gstack/ went out that way.
# Nothing the plugin needs at runtime begins with a dot.
zip -r $ZIP_NAME . \
    -x ".*" \
    -x "*/.*" \
    -x "node_modules/*" \
    -x "tests/*" \
    -x "svn/*" \
    -x "resources/*" \
    -x "build.sh" \
    -x "phpstan.neon" \
    -x "webpack.config.js" \
    -x "translation.node.js" \
    -x "webpack.mix.js" \
    -x "vitest.config.mjs" \
    -x "package.json" \
    -x "package-lock.json" \
    -x "pnpm-lock.yaml" \
    -x "composer.lock" \
    -x "README.md" \
    -x "CLAUDE.md" \
    -x "research/*" \
    -x "internal_docs/*"

echo "✅ Build Created: $ZIP_NAME"

# 4. Restore Dev Dependencies
echo "🔄 Restoring Dev Dependencies..."
composer install

# 5. Verify the archive
# The exclusion list is a denylist, so anything new is included by default and
# is only caught by someone reading the zip. This fails the build instead.
echo "🔍 Verifying $ZIP_NAME..."
LEAKED=$(unzip -Z1 "$ZIP_NAME" | grep -E '^(\.|node_modules/|tests/|resources/|research/|internal_docs/|svn/)' || true)

if [ -n "$LEAKED" ]; then
    echo "❌ Development files found in $ZIP_NAME:"
    echo "$LEAKED" | sed 's/^/     /'
    echo "   Add them to the exclusion list in build.sh and rebuild."
    exit 1
fi

# assets/ is gitignored but generated by step 1, so an empty one means the
# frontend build silently did nothing and the zip ships a plugin with no UI.
if [ -z "$(unzip -Z1 "$ZIP_NAME" | grep '^assets/')" ]; then
    echo "❌ $ZIP_NAME contains no assets/ - the frontend build did not run."
    exit 1
fi

echo "🎉 Build Complete! You can now upload $ZIP_NAME to WordPress."
